default: MessageCS.class MessageSC.class ServidorArchivos.class

MessageCS.class: MessageCS.java
	javac MessageCS.java
MessageSC.class: MessageSC.java
	javac MessageSC.java
ServidorArchivos.class: ServidorArchivos.java
	javac ServidorArchivos.java
clean: 
	rm *.class