
juego: Edgar_Augusto_Santiago_Nieves_DSD_4CM4_3.o gfxModified.o
	g++ Edgar_Augusto_Santiago_Nieves_DSD_4CM4_3.o gfxModified.o -o juego -lX11 -lm
juego.o: Edgar_Augusto_Santiago_Nieves_DSD_4CM4_3.cpp gfxModified.o
	g++ Edgar_Augusto_Santiago_Nieves_DSD_4CM4_3.cpp -c
gfxModified.o: gfxModified.c gfxModified.h
	gcc gfxModified.c -c