compile: PaqueteDatagrama.o SocketDatagrama.o
	g++ Respuesta.cpp servidor.cpp  PaqueteDatagrama.o SocketDatagrama.o -o servidor
	g++ Solicitud.cpp cliente.cpp  PaqueteDatagrama.o SocketDatagrama.o -o cliente
PaqueteDatagrama.o:
	g++ -c PaqueteDatagrama.cpp
SocketDatagrama.o:
	g++ -c SocketDatagrama.cpp
Solicitud.o:
	g++ -c Solicitud.cpp
