2: 2.cpp Fraccion.o
	g++ 2.cpp Fraccion.o -o 2
Fraccion.o: Fraccion.cpp Fraccion.h
	g++ Fraccion.cpp -c
1: 1.cpp Temperatura.o
	g++ 1.cpp Temperatura.o -o 1
Temperatura.o: Temperatura.cpp Temperatura.h
	g++ Temperatura.cpp -c