1: 1.cpp Rectangulo.o
	g++ 1.cpp Rectangulo.o Coordenada.o -o 1
Rectangulo.o: Rectangulo.cpp Coordenada.o Rectangulo.h
	g++ Rectangulo.cpp -c
Coordenada.o: Coordenada.cpp Coordenada.h
	g++ Coordenada.cpp -c