file_server_objetos1: file_server_objetos1.cpp PaqueteDatagrama.o SocketDatagrama.o header.h

	g++ file_server_objetos1.cpp PaqueteDatagrama.o SocketDatagrama.o -o file_server_objetos1


PaqueteDatagrama.o: PaqueteDatagrama.cpp PaqueteDatagrama.h	

	g++ PaqueteDatagrama.cpp -c



SocketDatagrama.o: SocketDatagrama.cpp SocketDatagrama.h

	g++ SocketDatagrama.cpp -c

