.PHONY: run
run: Alan_Fernando_Rincon_Vieyra_DSD_4CV2_2
	./Alan_Fernando_Rincon_Vieyra_DSD_4CV2_2

gfx.o: gfx.c
	gcc gfx.c -c

Alan_Fernando_Rincon_Vieyra_DSD_4CV2_2: Alan_Fernando_Rincon_Vieyra_DSD_4CV2_2.cpp
	g++ gfx.o Alan_Fernando_Rincon_Vieyra_DSD_4CV2_2.cpp -o Alan_Fernando_Rincon_Vieyra_DSD_4CV2_2 -lX11
